#!/bin/sh
umask 002
#export GIT_WORK_TREE=..
#git submodule init
#git submodule update --remote
#git submodule update
git checkout -f
git update-server-info
git submodule update --init --recursive -f
cd ..
make
